# Generated by Django 3.2.4 on 2021-06-09 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('patio', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=50)),
                ('trivia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='happyhourscourapi.business')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('happy_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyhourscourapi.happyhour')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyhourscourapi.customer')),
                ('happy_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyhourscourapi.happyhour')),
            ],
        ),
        migrations.AddField(
            model_name='happyhour',
            name='special_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='happyhourscourapi.specialtype'),
        ),
        migrations.AddField(
            model_name='happyhour',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='happyhourscourapi.weekday'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyhourscourapi.customer')),
                ('happy_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_happy_hour', to='happyhourscourapi.happyhour')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='happyhourscourapi.businesstype'),
        ),
    ]
