# Generated by Django 3.2.4 on 2021-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyhourscourapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='happyhour',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
