# Generated by Django 3.2.4 on 2021-06-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyhourscourapi', '0002_auto_20210610_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='happyhour',
            name='description',
        ),
        migrations.AddField(
            model_name='happyhour',
            name='beer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='happyhour',
            name='food',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='happyhour',
            name='liquor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='happyhour',
            name='wine',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='happyhourscourapi.location'),
        ),
    ]
