# Generated by Django 3.2.4 on 2021-06-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyhourscourapi', '0004_alter_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='happyhour',
            name='end_time',
            field=models.TimeField(default='7:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='happyhour',
            name='start_time',
            field=models.TimeField(default='5:00'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
